var studios = [
    {
        "id": 0,
        "username": "loudhouse",
        "studioName": "Loudhouse Band Rehearsal Studio",
        "address": "40, T. Gener, corner K-1st, Kamuning, Quezon City, 1103 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": true,
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 1,
        "username": "bluelight",
        "studioName": "Blue Light Recording And Rehearsal Studios",
        "address": "2nd Floor FORAB Building, 121 Kamuning Road, Diliman, Quezon City, 1103 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4251290,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 2,
        "username": "iconmusic",
        "studioName": "Icon Music Studios Philippines",
        "address": "165 Tomas Morato, L/G Thompson Square Building, Quezon City",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 8978716,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 3,
        "username": "towerofdoom",
        "studioName": "Tower of Doom Records",
        "address": "4th Floor Armon Bldg., Corner Anonas Rd. and Kamias Rd., Quezon City, 1211 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 4,
        "username": "onair",
        "studioName": "On-Air Studio",
        "address": "2/F Stall 18 Cubao Expo, Gen. Romulo Avenue , Cubao, Quezon City, Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09468848300",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 5,
        "username": "propaganda",
        "studioName": "Propaganda",
        "address": "97 Annapolis ST, Cubao, Quezon City, 1102 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09209610348",
        "landline": 6647958,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 6,
        "username": "jaxband",
        "studioName": "Jax Band Rehearsal Studio",
        "address": "Block 4, Lot 11 and 12, St.Francis Village, San Bartolome, Novaliches, Quezon City, 1123 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 3555623,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 7,
        "username": "sacrednoize",
        "studioName": "Sacrednoize Band Rehearsal Studio",
        "address": "1, Susana Street, corner Quirino Hi-Way, Barangay Gulod, Quezon City, 1117 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09277789599",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 8,
        "username": "blueroom",
        "studioName": "The Blueroom Band Rehearsal Studio",
        "address": "72 Maginhawa, Diliman, Lungsod Quezon, 1101 Kalakhang Maynila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09155000000",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 9,
        "username": "pinoypenguin",
        "studioName": "Pinoy Penguin Band Rehearsal Studio",
        "address": "84 Kamias Rd, Quezon City, Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09053605880",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 10,
        "username": "noisecurb",
        "studioName": "Noise Curb Band Rehearsal Studio",
        "address": "1840, Room 104 Vir Building, E Rodriguez Sr Avenue, Cubao, Quezon City, 1109 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 7244508,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 11,
        "username": "rednoise",
        "studioName": "Red Noise Band Rehearsal Studio",
        "address": "1D, Susana Street, corner Quirino Highway, Barangay Gulod, Quezon City, 1117 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4156887,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 12,
        "username": "impluwensia",
        "studioName": "Impluwensia Band Rehearsal Studio",
        "address": "2nd Floor, Citi Mall Philcoa, Diliman, Quezon City, 1101 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 5122092,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 13,
        "username": "musicschool",
        "studioName": "Music School and Band Rehearsal Studio",
        "address": "Royal Midway Plaza, Tandang Sora Avenue, Culiat , Culiat , 1128 Quezon City , Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09161480294",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 14,
        "username": "housebased",
        "studioName": "House Based Band Rehearsal Studio",
        "address": "Barangay Doña Imelda156 Kapiligan Street, Quezon City, 1113 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 3530050,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 15,
        "username": "joctv",
        "studioName": "JocTV Recording and Rehearsal Studios",
        "address": "Basement Level, A&M Building, Commonwealth Avenue, Batasan Hills, Quezon City",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4274333,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 16,
        "username": "muzikademy",
        "studioName": "Muzikademy Band Rehearsal Studio",
        "address": "Block 6, Lot 2, Jordan Plains, Phase 4, Don Mariano Avenue, Quezon City, 1100 Metro Manil",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 9214686,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 17,
        "username": "mrsmusical",
        "studioName": "MRS Musical Rehearsal Studio",
        "address": "100 Maginhawa St., Teachers Village East Diliman, Quezon City, 1101 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09159297018",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 18,
        "username": "antracks",
        "studioName": "Antracks Band Rehearsal Studio",
        "address": "Kalusugan, Quezon City, Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09297859757",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 19,
        "username": "thirdline",
        "studioName": "The Thirdline Studio",
        "address": "129 Esteban Abada St, Quezon City, 1108 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4260103,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 20,
        "username": "knrband",
        "studioName": "KNR Band Studio",
        "address": "149 a j building, Ermin Garcia Ave, Cubao, Quezon City, Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09185283902",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 21,
        "username": "bandroom",
        "studioName": "Bandroom Kamuning",
        "address": "40 Kamuning Rd, near corner Judge Jimenez (Sct Ybardaloza), Quezon City, 1103 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09178939932",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 22,
        "username": "hrjstudio",
        "studioName": "HRJ Band Rehearsal Studio",
        "address": "2178, Maria Clara Street, corner Blumentritt Street, Sampaloc, Manila, 1015 Metro Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 7420475,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 23,
        "username": "cleartone",
        "studioName": "Clear Tone Band Rehearsal Studio",
        "address": "678, D. Santiago, Corner Pelaez Streets, Manila, 1000 Metro Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 7168864,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 24,
        "username": "8thnote",
        "studioName": "8th Note Studios",
        "address": "Unit 201 Jajaj Building, 109 Panay Avenue, Quezon City, 1100 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4166665,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 25,
        "username": "redhouse",
        "studioName": "Red House Band Rehearsal Studio",
        "address": "Epifanio de los Santos Ave, Mandaluyong, Metro Manila",
        "city": "Mandaluyong",
        "latitude": "",
        "longitude": "",
        "mobile": "09065540359",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 26,
        "username": "musiczone",
        "studioName": "Music Zone Band Rehearsal Studio",
        "address": "E. Dela Paz Street, Marikina, Metro Manila",
        "city": "Marikina",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 27,
        "username": "blackchord",
        "studioName": "Black Chord Band Rehearsal Studio",
        "address": "3980 Ramon Magsaysay Blvd STA Mesa, Bgy 587, Zone 058 Sampaloc, Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 28,
        "username": "silverback",
        "studioName": "Silverback Rehearsal Studio",
        "address": "#100, Sct. De Guia, corner T. Morato, Quezon City 1103 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 7382938,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 29,
        "username": "transmetal",
        "studioName": "Transmetal Band Rehearsal Studio",
        "address": "210-D Samson Rd, Caloocan, 1400 Metro Manila",
        "city": "Caloocan",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 3654575,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 30,
        "username": "soundbox",
        "studioName": "Sound Box Band Rehearsal Studio",
        "address": "1411, Juan Luna Street, Tondo, Manila City",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4041778,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 31,
        "username": "cybershed",
        "studioName": "Cyber Shred Band Rehearsal Studio",
        "address": "587 Molino St., STA Quiteria Baesa Road 162 Caloocan City Metro Manila",
        "city": "Caloocan",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 32,
        "username": "rjcstudios",
        "studioName": "RJC Audio Recording & Rehearsal Studios",
        "address": "1815 Dapitan St, Sampaloc, Manila, Metro Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 7085606,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 33,
        "username": "soundkitchen",
        "studioName": "SoundKitchen Studio",
        "address": "19, Malingap, Quezon City, 1101 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09062537713",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 34,
        "username": "itarget",
        "studioName": "iTarget Rehearsal Studio",
        "address": "Bernal St, Pasig, 1609 Metro Manila",
        "city": "Pasig",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 3409538,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 35,
        "username": "8august",
        "studioName": "8AUGUST Rehearsal Studio",
        "address": "Gen.Malvar, San Antonio, Pasig, 1600 Metro Manila",
        "city": "Pasig",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 9100212,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 36,
        "username": "gigmaker",
        "studioName": "Gigmaker Band Rehearsal Studio",
        "address": "3rd Flr J. Center Bldg, Vista Verde Ave, Cainta, Metro Manila",
        "city": "Rizal",
        "latitude": "",
        "longitude": "",
        "mobile": "09333346162",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 37,
        "username": "pimpstudios",
        "studioName": "Pimp Studios",
        "address": "158, Calamba Street, corner Sto. Domingo, Quezon City, 1114 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09166621911",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 38,
        "username": "rockjock",
        "studioName": "RockJock Studios",
        "address": "Jordan Plains1535 Joshua Street Novaliches, Quezon City, 1123 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4184687,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 39,
        "username": "strawberryjams",
        "studioName": "Strawberry Jams Music Studio",
        "address": "258 Morato Street corner Scout Fernandez Street, Barangay Sacred Heart, Diliman, Quezon City, 1103",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09178817663",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 40,
        "username": "audiosynthesis",
        "studioName": "Audio Synthesis Rehearsal Studio",
        "address": "J.P Rizal Street, Manggahan, Rodriguez, 1860 Rizal",
        "city": "Rizal",
        "latitude": "",
        "longitude": "",
        "mobile": "09216487665",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 41,
        "username": "korazine",
        "studioName": "Korazine Rehearsal Studio",
        "address": "1832 Oroquieta St, Bgy 336, Zone 034 STA Cruz, Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 42,
        "username": "musikmanila",
        "studioName": "Musik Manila",
        "address": "1372, Sampaloc, Manila, Metro Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "09178626452",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 43,
        "username": "versionone",
        "studioName": "Version One Rehearsal Studio",
        "address": "322 G.Tuazon Street, Corner Lacson Avenue Sampaloc, Manila, 1008 Metro Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4824175,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 44,
        "username": "soundcheck",
        "studioName": "Soundcheck Band Rehearsal Studio",
        "address": "1609 a Francisco St San Andres, Bgy 802, Zone 087 Sta Ana, Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 45,
        "username": "soundquotient",
        "studioName": "Sound Quotient Studios",
        "address": "154 Maginhawa, Diliman, Lungsod Quezon, Kalakhang Maynila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 46,
        "username": "kapatid",
        "studioName": "Kapatid Band Rehearsal Studio",
        "address": "Narra, Makati, 1214 Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 7013613,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 47,
        "username": "influence",
        "studioName": "Influence Recording Studio",
        "address": "2nd Floor, # 7 Scout Borromeo, South Triangle, Diliman, Quezon City, Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 48,
        "username": "onepop",
        "studioName": "One Pop Band Studio",
        "address": "51 B Tandang Sora Avenue, Quezon City, 1100 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4553228,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 49,
        "username": "talentasia",
        "studioName": "Talent Asia Rehearsal and Recording Studio",
        "address": "3rd floor Northridge Plaza Congressional Ave, Quezon City, 1100 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 9278133,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 50,
        "username": "muzikart",
        "studioName": "MusikArt Band Rehearsal Studio",
        "address": "Lot 25, Block 6, Phase 6, Sagebrush Street, Greenland Executive Village, San Juan, Cainta, 1900 Rizal",
        "city": "Rizal",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 6559844,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 51,
        "username": "dredd1",
        "studioName": "Dredd1 Band Rehearsal Studio",
        "address": "905-D, Mandaluyong City, Manila, 1150 Metro Manila",
        "city": "Mandaluyong",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 52,
        "username": "emusic",
        "studioName": "E-Music Band Rehearsal Studios",
        "address": "Basement Oppen Building, 349 Senator Gil Puyat Avenue or Jupiter Street, Makati, 1224 Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 8848747,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 53,
        "username": "museomusic",
        "studioName": "Museo Music Studios Inc.",
        "address": "Units ABC RGH Bldg, #3 Timog Ave. cor. Panay, Quezon City",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4134313,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 54,
        "username": "kwerdaz",
        "studioName": "Kwerdaz Band Rehearsal Studio",
        "address": "1180 Tayuman St, Bgy 235, Zone 022 Tondo, Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 55,
        "username": "btmtstudio",
        "studioName": "BTMT Band Rehearsal Studio",
        "address": "1013 C Zobel St, Bgy 660, Zone 071 Ermita, Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 56,
        "username": "rockman",
        "studioName": "Rockman Music Studio",
        "address": "86 M.H. del Pilar St, Pasig, Metro Manila",
        "city": "Pasig",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 6256830,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 57,
        "username": "soundbay",
        "studioName": "Sound Bay Studio",
        "address": "24, Ateneo Road, Kingsville Subdivision, Barangay Mayamot, Antipolo City, Rizal",
        "city": "Rizal",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 58,
        "username": "hapijoey",
        "studioName": "Hapijoey Recording Studio",
        "address": "1423 AH Lacson St. Governor Forbes, Santa Cruz, Manila, Metro Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "09173032407",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": true,
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "https://www.facebook.com/hapijoey",
        "website": "http://www.hapijoey.com/"
    },
    {
        "id": 59,
        "username": "pointbee",
        "studioName": "Pointbee Multimedia Recording Studio",
        "address": "8 Madasalin St, Sikatuna Village, Quezon City, Metro Manil",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09178518661",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": true,
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "https://www.facebook.com/PointbeeMultimedia",
        "website": "http://www.pointbeemultimedia.com/"
    },
    {
        "id": 60,
        "username": "solidbrown",
        "studioName": "Solidbrown Recording Studio",
        "address": "165 Molave corner Batino Street, Project 3, Quezon City, Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": true,
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "https://www.facebook.com/solidbrownrecordingstudio",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 61,
        "username": "neusound",
        "studioName": "Neu Sound Studio",
        "address": "2F AJ Bldg. 149 Ermin Garcia St. Cubao, Quezon City, 1109",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "09176269705",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 62,
        "username": "hardcore",
        "studioName": "Hard Core Band Rehersal Studio",
        "address": "50 E.Rodriguez Sr Ave, Rodriguez, Rizal, 1860 Rizal",
        "city": "Rizal",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 6971702,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 63,
        "username": "studio8191",
        "studioName": "Studio 8191",
        "address": "8191 Constancia St., Makati, Philippines, Makati, 1207 Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 8992204,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 64,
        "username": "wiredstudio",
        "studioName": "Wired Band Rehearsal and Recording Studio",
        "address": "2815 E. Zobel Street Corner Mabini Street, Makati, 1210 Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 5093382,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 65,
        "username": "islamuzika",
        "studioName": "Isla Musika Rehearsal Studios",
        "address": "6264 Estacion, Unit 57 to 59 Cityland Building, 1230 Metro Manila, Makati, 1230 Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "09175216585",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 66,
        "username": "studio9",
        "studioName": "Studio 9 Band Rehearsal",
        "address": "7236 J. Victor Street, Barangay Pio del Pilar, Makati, 1230 Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "09175195891",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 67,
        "username": "neversleep",
        "studioName": "Neversleep Music Studio",
        "address": "26 C Rd 3, Project 6, Quezon City, 1100 Metro Manila",
        "city": "Quezon City",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4565836,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 68,
        "username": "auralcanvas",
        "studioName": "Aural Canvas Records",
        "address": "1 Xavier Street\nMarikina, 1803 Metro Manila\nPhilippines",
        "city": "Marikina",
        "latitude": "",
        "longitude": "",
        "mobile": "09224818344",
        "landline": "",
        "email": "",
        "rehearsal": true,
        "recording": true,
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 69,
        "username": "studiom",
        "studioName": "Studio M Rehearsal and Recording",
        "address": "9699 Pililla, Makati, 1202 Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 9755630,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 70,
        "username": "blackbox",
        "studioName": "Black Box Band Rehearsal Studio",
        "address": "Bagumbong, 171, Caloocan, 1421 Metro Manila",
        "city": "Caloocan",
        "latitude": "",
        "longitude": "",
        "mobile": "09267177059",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 71,
        "username": "aljels",
        "studioName": "ALJELS Band Rehearsal Studio",
        "address": "37 A Col. Estacio St Palingon Tipas, Manila, Metro Manila",
        "city": "Manila",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 72,
        "username": "starstudio",
        "studioName": "STAR / Studio and Band Rehearsal",
        "address": "E.P. Village Western Bicutan Phase 1 Block 20 Lot 08, Taguig, 1630 Metro Manila",
        "city": "Taguig",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 8390495,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 73,
        "username": "skunk",
        "studioName": "Skunk Productions Recording Studio",
        "address": "84-C San Francisco Street, Barangay Kapitolyo, Metro Manila, Pasig, 1603",
        "city": "Pasig",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 6332496,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "http://skunkproductions.com/"
    },
    {
        "id": 74,
        "username": "euphony",
        "studioName": "Euphony Music Center and Studio",
        "address": "F-8, Mezzanine Makati Cinema Square, Chino Roces Avenue, Makati City, Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 8445289,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 75,
        "username": "yellowroom",
        "studioName": "Yellow Room Music Philippines",
        "address": "19 General Delgado, San Antonio, Pasig, 1600 Metro Manila",
        "city": "Pasig",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 4034814,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 76,
        "username": "rockofages",
        "studioName": "Rock of Ages Music Studio",
        "address": "Unit 205, 2nd floor, UPY Building, Gil Puyat (Buendia) Ave. corner Marconi St., Makati City, Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "09437969155",
        "landline": "",
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 77,
        "username": "spryta",
        "studioName": "Spryta Productions, Inc. Recording Studio",
        "address": "Unit 606 Globe Telecom Plaza, Pioneer Highlands Condominium, Madison, Mandaluyong, Metro Manila",
        "city": "Mandaluyong",
        "latitude": "",
        "longitude": "",
        "mobile": "09055515472",
        "landline": 6617941,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "https://www.facebook.com/Spryta-Productions-Inc-268898366519806/",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    },
    {
        "id": 78,
        "username": "soundweavers",
        "studioName": "SoundWeavers Recording Studio & Production, Inc.",
        "address": "Cityland Pasong Tamo Tower 2808 Cityland Pasong Tamo Tower, 2210 Don Chino Roces Ave., Makati Metro Manila",
        "city": "Makati",
        "latitude": "",
        "longitude": "",
        "mobile": "",
        "landline": 7295243,
        "email": "",
        "rehearsal": "",
        "recording": "",
        "schedule": "",
        "rehearsalminhourlyrate": "",
        "rehearsalmaxhourlyrate": "",
        "facebook": "",
        "website": "",
        "status": "",
        "pics": "default",
        "schedule": ""
    }
];

exports.findAll = function (req, res, next) {
    var name = req.query.name;
    if (name) {
        res.send(studios.filter(function(studio) {
            return (studio.studioName + ' ' + studio.address).toLowerCase().indexOf(name.toLowerCase()) > -1;
        }));
    } 
    else {
        res.send(studios);
    }
};

exports.findById = function (req, res, next) {
    var id = req.params.id;
    res.send(studios[id]);
};